_target_: src.datasets.huggingface_dataset.KaggleBirdClefDataset
data_path: ${connected_dir}/data
split: ${split.train}
split_ratio: ${split_ratio}
seed: ${seed}
target_column_name: ${target_column_name}
num_devices: ${devices}
batch_size: ${batch_size}
sampling_rate: ${sampling_rate}
num_mels: ${num_mels}
max_length: ${max_length}
pretrained_model_name: ${pretrained_model_name}
preprocess_type: ${preprocess_type}
