# @package _global_
defaults:
  - dataset: wav2vec_kagglebirdclef_dataset
  - architecture: huggingface_architecture
  - tuner: huggingface_tuner
  - logger: wandb
  - hydra: hydra
  - callbacks: callbacks
  - trainer: trainer

package_name: kaggle-bird-clef-2024
project_dir: /home/ubuntu/${package_name}
connected_dir: /data/${package_name}

seed: 2024

num_labels: 25

split:
  train: train
  val: val
  test: test
  predict: predict

batch_size: 24

split_ratio: 0.1
target_column_name: label
upload_user: microsoft
model_type: swinv2-large-patch4-window12to16-192to256-22kto1k-ft
pretrained_model_name: ${upload_user}/${model_type}

lr: 0.00002
t_max: 50
eta_min: 0.0000025

monitor: val_MulticlassF1Score
tracking_direction: max
patience: 3
min_delta: 0

devices: 1
accelerator: gpu
strategy: auto
log_every_n_steps: 10
precision: 32
accumulate_grad_batches: 1
epoch: 100

model_name: HuggingFace
dataset_name: KaggleBirdClef2024
mode: train

is_tuned: tuned
num_trials: 3
hparams_save_path: ${connected_dir}/hparams/${model_name}/${dataset_name}/${num_trials}_trials
tuned_hparams_path: ${hparams_save_path}/best_params.json

project_name: ${model_name}-${dataset_name}-${mode}
total_batch_size: bs${batch_size}x${devices}x${accumulate_grad_batches}
save_detail: ${upload_user}_${model_type}-precision${precision}-${total_batch_size}
resumed_step: 0
ckpt_path: ${callbacks.model_checkpoint.dirpath}/epoch${epoch}.ckpt

submission_file_name: sample_submission
logit_name: ${save_detail}-epoch${epoch}
submission_name: ${save_detail}-epoch${epoch}

run_name: ${project_name}
work_dir: ${hydra:runtime.cwd}